name: dependabot-build

on: pull_request

jobs:
  dependabot-build:
    # Check if the PR is not raised by this workflow and is not from a fork
    if: startsWith(github.head_ref, 'dependabot-build') == false && startsWith(github.head_ref, 'dependabot') == true && github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm i
        env:
          CI: true
      - name: Run test build
        run: npm run build
      - name: Set dependabot-build branch name
        id: vars
        run: echo ::set-output name=branch-name::"dependabot-build/${{ github.head_ref }}"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "chore(build): build assets"
          title: "chore(build): build assets"
          body: This is an auto-generated PR to build assets changed by Dependabot.
          labels: dependencies
          branch: ${{ steps.vars.outputs.branch-name }}
